server {
  listen 80;
  server_name _;
  client_max_body_size 100m;

  location /media/ {
    alias /data/media/public/;
    try_files $uri =404;
    add_header Cache-Control "public, max-age=2592000";
  }

  location / {
    proxy_pass http://public-web/;
    proxy_set_header Host $host;
  }
}
